// Code generated by hertz generator.

package main

import (
	"context"
	"os"
	"time"

	"gomall/app/frontend/biz/dal"
	"gomall/app/frontend/biz/router"
	"gomall/app/frontend/conf"
	"gomall/app/frontend/infra/rpc"
	"gomall/app/frontend/middleware"

	"github.com/bobobobn/gomall/common/mtl"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	prometheus "github.com/hertz-contrib/monitor-prometheus"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	"github.com/joho/godotenv"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

func main() {
	// init dal
	err := godotenv.Load()
	if err != nil {
		hlog.Fatal(err)
	}
	dal.Init()
	rpc.InitClient()
	r, rInfo := mtl.InitMetrics(conf.GetConf().Hertz.Service, conf.GetConf().Hertz.MetricsPort, conf.GetConf().Registry.RegistryAddress[0])
	defer r.Deregister(rInfo)
	address := conf.GetConf().Hertz.Address
	h := server.New(server.WithHostPorts(address),
		server.WithTracer(prometheus.NewServerTracer("", "",
			prometheus.WithDisableServer(true), prometheus.WithRegistry(mtl.Registry))),
	)

	registerMiddleware(h)
	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})
	h.GET("/sign-in", func(c context.Context, ctx *app.RequestContext) {
		next := ctx.Query("next")
		if next == "" {
			next = ctx.Request.Header.Get("referer")
		}
		data := utils.H{
			"Title": "Sign In",
			"next":  next,
		}
		ctx.HTML(consts.StatusOK, "sign-in", data)
	})
	h.GET("/sign-up", func(c context.Context, ctx *app.RequestContext) {
		data := utils.H{
			"Title": "Sign Up",
		}
		ctx.HTML(consts.StatusOK, "sign-up", data)
	})
	h.GET("/about", func(c context.Context, ctx *app.RequestContext) {
		data := utils.H{
			"Title": "About",
		}
		ctx.HTML(consts.StatusOK, "about", data)
	})
	h.LoadHTMLGlob("template/*")
	h.Static("/static", "./")

	router.GeneratedRegister(h)

	h.Spin()
}

func registerMiddleware(h *server.Hertz) {
	// log
	logger := hertzlogrus.NewLogger()
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: time.Minute,
	}
	hlog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())

	// session
	store, err := redis.NewStore(10, "tcp", conf.GetConf().Redis.Address, "", []byte(os.Getenv("SESSION_SECRET")))
	if err != nil {
		hlog.Fatal(err)
	}
	h.Use(sessions.New("gomall", store))

	middleware.Register(h)
}
